openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/malwares/:
    get:
      operationId: listMalwares
      description: 'ViewSet used to render Malware objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Malware'
          description: ''
      tags:
      - malwares
    post:
      operationId: createMalware
      description: 'ViewSet used to render Malware objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Malware'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Malware'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Malware'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Malware'
          description: ''
      tags:
      - malwares
  /api/malwares/{sha256}/:
    get:
      operationId: retrieveMalware
      description: 'ViewSet used to render Malware objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: sha256
        in: path
        required: true
        description: A unique value identifying this malware.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Malware'
          description: ''
      tags:
      - malwares
    delete:
      operationId: destroyMalware
      description: 'ViewSet used to render Malware objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: sha256
        in: path
        required: true
        description: A unique value identifying this malware.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - malwares
  /api/malwares/{sha256}/download/:
    get:
      operationId: downloadMalware
      description: Extra endpoint to download the malware.
      parameters:
      - name: sha256
        in: path
        required: true
        description: A unique value identifying this malware.
        schema:
          type: string
      responses:
        '200':
          content:
            ? ''
            : schema:
                $ref: '#/components/schemas/Malware'
          description: ''
      tags:
      - malwares
  /api/workers/:
    get:
      operationId: listWorkers
      description: 'ViewSet used to render Worker objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Worker'
          description: ''
      tags:
      - workers
    post:
      operationId: createWorker
      description: 'ViewSet used to render Worker objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Worker'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Worker'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Worker'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
          description: ''
      tags:
      - workers
  /api/workers/{id}/:
    get:
      operationId: retrieveWorker
      description: 'ViewSet used to render Worker objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this worker.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
          description: ''
      tags:
      - workers
    delete:
      operationId: destroyWorker
      description: 'ViewSet used to render Worker objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this worker.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - workers
  /api/workers/{id}/get_task/:
    get:
      operationId: getTaskWorker
      description: 'Extra API endpoint being called by Windows Agent to find a

        job to do. Gives every needed information to the Agent and

        update objects states accordingly.'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this worker.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
          description: ''
      tags:
      - workers
  /api/jobs/:
    get:
      operationId: listJobs
      description: 'ViewSet used to render Job objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
          description: ''
      tags:
      - jobs
    post:
      operationId: createJob
      description: 'ViewSet used to render Job objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Job'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
      tags:
      - jobs
  /api/jobs/{id}/:
    get:
      operationId: retrieveJob
      description: 'ViewSet used to render Job objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this job.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
      tags:
      - jobs
    delete:
      operationId: destroyJob
      description: 'ViewSet used to render Job objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this job.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - jobs
  /api/jobs/{id}/download_results/:
    get:
      operationId: downloadResultsJob
      description: Extra endpoint to download the results associated to a Job.
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this job.
        schema:
          type: string
      responses:
        '200':
          content:
            ? ''
            : schema:
                $ref: '#/components/schemas/Job'
          description: ''
      tags:
      - jobs
  /api/datasets/:
    get:
      operationId: listDatasets
      description: 'ViewSet used to render Dataset objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
          description: ''
      tags:
      - datasets
    post:
      operationId: createDataset
      description: 'ViewSet used to render Dataset objects to user.

        It does not allow modification of existing objects.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dataset'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Dataset'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Dataset'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          description: ''
      tags:
      - datasets
  /api/datasets/{id}/:
    get:
      operationId: retrieveDataset
      description: 'ViewSet used to render Dataset objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this dataset.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          description: ''
      tags:
      - datasets
    delete:
      operationId: destroyDataset
      description: 'ViewSet used to render Dataset objects to user.

        It does not allow modification of existing objects.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this dataset.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - datasets
  /api/datasets/{id}/download/:
    get:
      operationId: downloadDataset
      description: Extra endpoint to download the zipfile associated to a Dataset.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this dataset.
        schema:
          type: string
      responses:
        '200':
          content:
            ? ''
            : schema:
                $ref: '#/components/schemas/Dataset'
          description: ''
      tags:
      - datasets
  /api/stats/:
    get:
      operationId: listStats
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - stats
  /api/rules/:
    get:
      operationId: listRuleForms
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - rules
    post:
      operationId: createRuleForm
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - rules
    delete:
      operationId: destroyRuleForm
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - rules
  /api/workers/{id}/submit_results/:
    post:
      operationId: submitResultsWorker
      description: 'Extra API endpoint used by the Windows Agent to submit results

        of its job. The results are send through a file (currently being

        a JSON or a ZIP)/'
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this worker.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Worker'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Worker'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Worker'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
          description: ''
      tags:
      - workers
components:
  schemas:
    Malware:
      type: object
      properties:
        sha256:
          type: string
          readOnly: true
        file:
          type: string
          format: binary
          writeOnly: true
        jobs:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                readOnly: true
              results:
                type: string
                format: binary
                writeOnly: true
              job_type:
                enum:
                - PESieve
                - Detours
                type: string
              job_time:
                type: integer
                maximum: 2147483647
                minimum: -2147483648
              state:
                type: string
                readOnly: true
              extras_results:
                type: object
                readOnly: true
              creation_time:
                type: string
                format: date-time
                readOnly: true
              start_time:
                type: string
                format: date-time
                readOnly: true
              end_time:
                type: string
                format: date-time
                readOnly: true
              malware:
                type: string
            required:
            - job_type
            - malware
          readOnly: true
        state:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 128
        label:
          type: string
          maxLength: 50
        upload_time:
          type: string
          format: date-time
          readOnly: true
        md5:
          type: string
          readOnly: true
        sha512:
          type: string
          readOnly: true
        format:
          type: string
          maxLength: 3
        export_dll:
          type: string
          maxLength: 100
      required:
      - file
    Worker:
      type: object
      properties:
        id:
          type: string
          format: uuid
        ip:
          type: string
          readOnly: true
        registration_time:
          type: string
          format: date-time
          readOnly: true
        job:
          type: object
          properties:
            id:
              type: string
              format: uuid
              readOnly: true
            job_type:
              enum:
              - PESieve
              - Detours
              type: string
            job_time:
              type: integer
              maximum: 2147483647
              minimum: -2147483648
            state:
              type: string
              readOnly: true
            results:
              type: string
              format: binary
              readOnly: true
            extras_results:
              type: object
              readOnly: true
            creation_time:
              type: string
              format: date-time
              readOnly: true
            start_time:
              type: string
              format: date-time
              readOnly: true
            end_time:
              type: string
              format: date-time
              readOnly: true
            malware:
              type: string
          required:
          - job_type
          - malware
          readOnly: true
    Job:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        results:
          type: string
          format: binary
          writeOnly: true
        job_type:
          enum:
          - PESieve
          - Detours
          type: string
        job_time:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        state:
          type: string
          readOnly: true
        extras_results:
          type: object
          readOnly: true
        creation_time:
          type: string
          format: date-time
          readOnly: true
        start_time:
          type: string
          format: date-time
          readOnly: true
        end_time:
          type: string
          format: date-time
          readOnly: true
        malware:
          type: string
      required:
      - job_type
      - malware
    Dataset:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        file:
          type: string
          format: binary
          writeOnly: true
        status:
          type: string
          readOnly: true
        creation_time:
          type: string
          format: date-time
          readOnly: true
